# Generated by Django 3.0.3 on 2020-05-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spells',
            name='classes',
            field=models.CharField(default='Error', max_length=100),
        ),
        migrations.AlterField(
            model_name='features',
            name='featureName',
            field=models.CharField(default=1589558876.5065343, max_length=30),
        ),
        migrations.AlterField(
            model_name='spells',
            name='spellName',
            field=models.CharField(default=1589558876.505537, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='spells',
            name='spellNumber',
            field=models.IntegerField(default=1589558876.505537, primary_key=True, serialize=False, unique=True),
        ),
    ]
