# Generated by Django 3.0.3 on 2020-04-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='userID',
            field=models.IntegerField(default=-1),
        ),
    ]
