# Generated by Django 3.0.3 on 2020-04-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200409_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
