# Generated by Django 3.0.3 on 2020-04-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200409_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='temp_hitpoints',
            field=models.IntegerField(default=0),
        ),
    ]
