# Generated by Django 3.0.3 on 2020-04-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_character_temp_hitpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='senses',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
