# Generated by Django 3.0.3 on 2020-04-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_character_senses'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='armorProfs',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='toolProfs',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='weaponProfs',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
