# Generated by Django 3.0.3 on 2020-04-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200422_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='languageProfs',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
